 title: "monsterlist"
  2 author: "chisaipete"
  3 description: "A searchable pentaedition critter list."
  4 url: "https://guxuanzhen16.github.io"
  5 source-url: "https://github.com/guxuanzhen16/dominoes-and-dominicans"
  6 baseurl: "/dominoes-and-dominicans"
  7 exclude: ['Rakefile', 'README.md']
  8 collections:
  9   creatures:
 10     output: true
 11     permalink: "/creature/:name"
 12   tags:
 13     output: true
 14     permalink: "/tag/:name"

theme: jekyll-theme-tactile
