title: "Dominoes and Dominicans"
author: "chisaipete"
description: "A searchable pentadition Dom and Dom critter list."
url: "https://guxuanzhen16.github.io"
source-url: "https://github.com/guxuanzhen16/dominoes-and-dominicans"
baseurl: "/dominoes-and-dominicans"
exclude: ['Rakefile', 'README.md']
collections:
  creatures:
    output: true
    permalink: "/creature/:name"
  tags:
    output: true
    permalink: "/tag/:name"

theme: jekyll-theme-tactile
